import { db } from './db';
import { createCompetitionYear, upsertScripture, createGradeRule, enrollChildInBibleBee } from './bibleBee';

export async function seedBibleBeeDemo(opts?: { priorId?: string; currentId?: string }) {
    const now = new Date().toISOString();
    // Create 2024 and 2025 — if caller supplies ids, use them so seeded scriptures land in the expected competition years
    const y2024 = await createCompetitionYear({ id: opts?.priorId, year: 2024, name: 'Bible Bee 2024', description: 'Demo year 2024' });
    const y2025 = await createCompetitionYear({ id: opts?.currentId, year: 2025, name: 'Bible Bee 2025', description: 'Demo year 2025' });

    // seed scriptures for 2024 (sample) and a curated set for 2025
    for (let i = 1; i <= 10; i++) {
        await upsertScripture({ competitionYearId: y2024.id, reference: `Psalm ${i}:1`, text: `Sample scripture ${i} for 2024`, sortOrder: i });
    }

    // Full curated 2025 scriptures (flattened texts map with NIV/KJV/NLT)
    await upsertScripture({ competitionYearId: y2025.id, id: '1-2', reference: 'Philippians 4:4-5', text: `<sup>4</sup> Rejoice in the Lord always. I will say it again: Rejoice! <sup>5</sup> Let your gentleness be evident to all. The Lord is near.`, translation: 'NIV', texts: { NIV: `<sup>4</sup> Rejoice in the Lord always. I will say it again: Rejoice! <sup>5</sup> Let your gentleness be evident to all. The Lord is near.`, KJV: `<sup>4</sup> Rejoice in the Lord alway: and again I say, Rejoice. <sup>5</sup> Let your moderation be known unto all men. The Lord is at hand.`, NLT: `<sup>4</sup> Always be full of joy in the Lord. I say it again—rejoice! <sup>5</sup> Let everyone see that you are considerate in all you do. Remember, the Lord is coming soon.` }, sortOrder: 1 });
    await upsertScripture({ competitionYearId: y2025.id, id: '3', reference: 'Philippians 4:6', text: `<sup>6</sup> Do not be anxious about anything, but in every situation, by prayer and petition, with thanksgiving, present your requests to God.`, translation: 'NIV', texts: { NIV: `<sup>6</sup> Do not be anxious about anything, but in every situation, by prayer and petition, with thanksgiving, present your requests to God.`, KJV: `<sup>6</sup> Be careful for nothing; but in every thing by prayer and supplication with thanksgiving let your requests be made known unto God.`, NLT: `<sup>6</sup> Don’t worry about anything; instead, pray about everything. Tell God what you need, and thank him for all he has done.` }, sortOrder: 2 });
    await upsertScripture({ competitionYearId: y2025.id, id: '4', reference: 'Philippians 4:7', text: `<sup>7</sup> And the peace of God, which transcends all understanding, will guard your hearts and your minds in Christ Jesus.`, translation: 'NIV', texts: { NIV: `<sup>7</sup> And the peace of God, which transcends all understanding, will guard your hearts and your minds in Christ Jesus.`, KJV: `<sup>7</sup> And the peace of God, which passeth all understanding, shall keep your hearts and minds through Christ Jesus.`, NLT: `<sup>7</sup> Then you will experience God’s peace, which exceeds anything we can understand. His peace will guard your hearts and minds as you live in Christ Jesus.` }, sortOrder: 3 });
    await upsertScripture({ competitionYearId: y2025.id, id: '5', reference: 'Philippians 4:8', text: `<sup>8</sup> Finally, brothers and sisters, whatever is true, whatever is noble, whatever is right, whatever is pure, whatever is lovely, whatever is admirable—if anything is excellent or praiseworthy—think about such things.`, translation: 'NIV', texts: { NIV: `<sup>8</sup> Finally, brothers and sisters, whatever is true, whatever is noble, whatever is right, whatever is pure, whatever is lovely, whatever is admirable—if anything is excellent or praiseworthy—think about such things.`, KJV: `<sup>8</sup> Finally, brethren, whatsoever things are true, whatsoever things are honest, whatsoever things are just, whatsoever things are pure, whatsoever things are lovely, whatsoever things are of good report; if there be any virtue, and if there be any praise, think on these things.`, NLT: `<sup>8</sup> And now, dear brothers and sisters, one final thing. Fix your thoughts on what is true, and honorable, and right, and pure, and lovely, and admirable. Think about things that are excellent and worthy of praise.` }, sortOrder: 4 });
    await upsertScripture({ competitionYearId: y2025.id, id: '6', reference: 'Philippians 4:9', text: `<sup>9</sup> Whatever you have learned or received or heard from me, or seen in me—put it into practice. And the God of peace will be with you.`, translation: 'NIV', texts: { NIV: `<sup>9</sup> Whatever you have learned or received or heard from me, or seen in me—put it into practice. And the God of peace will be with you.`, KJV: `<sup>9</sup> Those things, which ye have both learned, and received, and heard, and seen in me, do: and the God of peace shall be with you.`, NLT: `<sup>9</sup> Keep putting into practice all you learned and received from me—everything you heard from me and saw me doing. Then the God of peace will be with you.` }, sortOrder: 5 });
    await upsertScripture({ competitionYearId: y2025.id, id: '7-8', reference: 'Philippians 4:12-13', text: `<sup>12</sup> I know what it is to be in need, and I know what it is to have plenty. I have learned the secret of being content in any and every situation, whether well fed or hungry, whether living in plenty or in want. <sup>13</sup> I can do all this through him who gives me strength.`, translation: 'NIV', texts: { NIV: `<sup>12</sup> I know what it is to be in need, and I know what it is to have plenty. I have learned the secret of being content in any and every situation, whether well fed or hungry, whether living in plenty or in want. <sup>13</sup> I can do all this through him who gives me strength.`, KJV: `<sup>12</sup> I know both how to be abased, and I know how to abound: every where and in all things I am instructed both to be full and to be hungry, both to abound and to suffer need. <sup>13</sup> I can do all things through Christ which strengtheneth me.`, NLT: `<sup>12</sup> I know how to live on almost nothing or with everything. I have learned the secret of living in every situation, whether it is with a full stomach or empty, with plenty or little. <sup>13</sup> For I can do everything through Christ, who gives me strength.` }, sortOrder: 6 });
    await upsertScripture({ competitionYearId: y2025.id, id: '9', reference: 'Philippians 4:19', text: `<sup>19</sup> And my God will meet all your needs according to the riches of his glory in Christ Jesus.`, translation: 'NIV', texts: { NIV: `<sup>19</sup> And my God will meet all your needs according to the riches of his glory in Christ Jesus.`, KJV: `<sup>19</sup> But my God shall supply all your need according to his riches in glory by Christ Jesus.`, NLT: `<sup>19</sup> And this same God who takes care of me will supply all your needs from his glorious riches, which have been given to us in Christ Jesus.` }, sortOrder: 7 });
    await upsertScripture({ competitionYearId: y2025.id, id: '10', reference: 'Lamentations 3:22', text: `<sup>22</sup> Because of the Lord’s great love we are not consumed, for his compassions never fail.`, translation: 'NIV', texts: { NIV: `<sup>22</sup> Because of the Lord’s great love we are not consumed, for his compassions never fail.`, KJV: `<sup>22</sup> It is of the Lord's mercies that we are not consumed, because his compassions fail not.`, NLT: `<sup>22</sup> The faithful love of the Lord never ends! His mercies never cease.` }, sortOrder: 8 });
    await upsertScripture({ competitionYearId: y2025.id, id: '11-12', reference: 'Matthew 7:1-2', text: `<sup>1</sup> Do not judge, or you too will be judged. <sup>2</sup> For in the same way you judge others, you will be judged, and with the measure you use, it will be measured to you.`, translation: 'NIV', texts: { NIV: `<sup>1</sup> Do not judge, or you too will be judged. <sup>2</sup> For in the same way you judge others, you will be judged, and with the measure you use, it will be measured to you.`, KJV: `<sup>1</sup> Judge not, that ye be not judged. <sup>2</sup> For with what judgment ye judge, ye shall be judged: and with what measure ye mete, it shall be measured to you again.`, NLT: `<sup>1</sup> Do not judge others, and you will not be judged. <sup>2</sup> For you will be treated as you treat others. The standard you use in judging is the standard by which you will be judged.` }, sortOrder: 9 });
    await upsertScripture({ competitionYearId: y2025.id, id: '13-14', reference: 'Matthew 7:3-4', text: `<sup>3</sup> Why do you look at the speck of sawdust in your brother’s eye and pay no attention to the plank in your own eye? <sup>4</sup> How can you say to your brother, ‘Let me take the speck out of your eye,’ when all the time there is a plank in your own eye?`, translation: 'NIV', texts: { NIV: `<sup>3</sup> Why do you look at the speck of sawdust in your brother’s eye and pay no attention to the plank in your own eye? <sup>4</sup> How can you say to your brother, ‘Let me take the speck out of your eye,’ when all the time there is a plank in your own eye?`, KJV: `<sup>3</sup> And why beholdest thou the mote that is in thy brother's eye, but considerest not the beam that is in thine own eye? <sup>4</sup> Or how wilt thou say to thy brother, Let me pull out the mote out of thine eye; and, behold, a beam is in thine own eye?`, NLT: `<sup>3</sup> And why worry about a speck in your friend’s eye when you have a log in your own? <sup>4</sup> How can you think of saying to your friend, ‘Let me help você get rid of that speck in your eye,’ when you can’t see past the log in your own eye?` }, sortOrder: 10 });
    await upsertScripture({ competitionYearId: y2025.id, id: '15', reference: 'Matthew 7:5', text: `<sup>5</sup> You hypocrite, first take the plank out of your own eye, and then you will see clearly to remove the speck from your brother’s eye.`, translation: 'NIV', texts: { NIV: `<sup>5</sup> You hypocrite, first take the plank out of your own eye, and then you will see clearly to remove the speck from your brother’s eye.`, KJV: `<sup>5</sup> Thou hypocrite, first cast out the beam out of thine own eye; and then shalt thou see clearly to cast out the mote out of thy brother's eye.`, NLT: `<sup>5</sup> Hypocrite! First get rid of the log in your own eye; then you will see well enough to deal with the speck in your friend’s eye.` }, sortOrder: 11 });
    await upsertScripture({ competitionYearId: y2025.id, id: '16', reference: 'Matthew 7:6', text: `<sup>6</sup> Do not give dogs what is sacred; do not throw your pearls to pigs. If you do, they may trample them under their feet, and turn and tear you to pieces.`, translation: 'NIV', texts: { NIV: `<sup>6</sup> Do not give dogs what is sacred; do not throw your pearls to pigs. If you do, they may trample them under their feet, and turn and tear you to pieces.`, KJV: `<sup>6</sup> Give not that which is holy unto the dogs, neither cast ye your pearls before swine, lest they trample them under their feet, and turn again and rend you.`, NLT: `<sup>6</sup> Don’t waste what is holy on people who are unholy. Don’t throw your pearls to pigs! They will trample the pearls, then turn and attack you.` }, sortOrder: 12 });
    await upsertScripture({ competitionYearId: y2025.id, id: '17-18', reference: 'Matthew 7:7-8', text: `<sup>7</sup> Ask and it will be given to you; seek and you will find; knock and the door will be opened to you. <sup>8</sup> For everyone who asks receives; the one who seeks finds; and to the one who knocks, the door will be opened.`, translation: 'NIV', texts: { NIV: `<sup>7</sup> Ask and it will be given to you; seek and you will find; knock and the door will be opened to you. <sup>8</sup> For everyone who asks receives; the one who seeks finds; and to the one who knocks, the door will be opened.`, KJV: `<sup>7</sup> Ask, and it shall be given you; seek, and ye shall find; knock, and it shall be opened unto you: <sup>8</sup> For every one that asketh receiveth; and he that seeketh findeth; and to him that knocketh it shall be opened.`, NLT: `<sup>7</sup> Keep on asking, and you will receive what you ask for. Keep on seeking, and you will find. Keep on knocking, and the door will be opened to you. <sup>8</sup> For everyone who asks, receives. Everyone who seeks, finds. And to everyone who knocks, the door will be opened.` }, sortOrder: 13 });
    await upsertScripture({ competitionYearId: y2025.id, id: '19-20', reference: 'Galatians 6:7-8', text: `<sup>7</sup> Do not be deceived: God cannot be mocked. A man reaps what he sows. <sup>8</sup> Whoever sows to please their flesh, from the flesh will reap destruction; whoever sows to please the Spirit, from the Spirit will reap eternal life.`, translation: 'NIV', texts: { NIV: `<sup>7</sup> Do not be deceived: God cannot be mocked. A man reaps what he sows. <sup>8</sup> Whoever sows to please their flesh, from the flesh will reap destruction; whoever sows to please the Spirit, from the Spirit will reap eternal life.`, KJV: `<sup>7</sup> Be not deceived; God is not mocked: for whatsoever a man soweth, that shall he also reap. <sup>8</sup> For he that soweth to his flesh shall of the flesh reap corruption; but he that soweth to the Spirit shall of the Spirit reap life everlasting.`, NLT: `<sup>7</sup> Don’t be misled—you cannot mock the justice of God. You will always harvest what you plant. <sup>8</sup> Those who live only to satisfy their own sinful nature will harvest decay and death from that sinful nature. But those who live to please the Spirit will harvest everlasting life from the Spirit.` }, sortOrder: 14 });
    await upsertScripture({ competitionYearId: y2025.id, id: '21', reference: '2 Timothy 1:7', text: `<sup>7</sup> For the Spirit God gave us does not make us timid, but gives us power, love and self-discipline.`, translation: 'NIV', texts: { NIV: `<sup>7</sup> For the Spirit God gave us does not make us timid, but gives us power, love and self-discipline.`, KJV: `<sup>7</sup> For God hath not given us the spirit of fear; but of power, and of love, and of a sound mind.`, NLT: `<sup>7</sup> For God has not given us a spirit of fear and timidity, but of power, love, and self-discipline.` }, sortOrder: 15 });
    await upsertScripture({ competitionYearId: y2025.id, id: '22-23', reference: 'Proverbs 3:5-6', text: `<sup>5</sup> Trust in the Lord with all your heart and lean not on your own understanding; <sup>6</sup> in all your ways submit to him, and he will make your paths straight.`, translation: 'NIV', texts: { NIV: `<sup>5</sup> Trust in the Lord with all your heart and lean not on your own understanding; <sup>6</sup> in all your ways submit to him, and he will make your paths straight.`, KJV: `<sup>5</sup> Trust in the Lord with all thine heart; and lean not unto thine own understanding. <sup>6</sup> In all thy ways acknowledge him, and he shall direct thy paths.`, NLT: `<sup>5</sup> Trust in the Lord with all your heart; do not depend on your own understanding. <sup>6</sup> Seek his will in all you do, and he will show you which path to take.` }, sortOrder: 16 });
    await upsertScripture({ competitionYearId: y2025.id, id: '24-25', reference: 'Proverbs 3:7-8', text: `<sup>7</sup> Do not be wise in your own eyes; fear the Lord and shun evil. <sup>8</sup> This will bring health to your body and nourishment to your bones.`, translation: 'NIV', texts: { NIV: `<sup>7</sup> Do not be wise in your own eyes; fear the Lord and shun evil. <sup>8</sup> This will bring health to your body and nourishment to your bones.`, KJV: `<sup>7</sup> Be not wise in thine own eyes: fear the Lord, and depart from evil. <sup>8</sup> It shall be health to thy navel, and marrow to thy bones.`, NLT: `<sup>7</sup> Don’t be impressed with your own wisdom. Instead, fear the Lord and turn away from evil. <sup>8</sup> Then you will have healing for your body and strength for your bones.` }, sortOrder: 17 });
    await upsertScripture({ competitionYearId: y2025.id, id: '26-27', reference: 'Numbers 6:24-26', text: `<sup>24</sup> The Lord bless you and keep you; <sup>25</sup> the Lord make his face shine on you and be gracious to you; <sup>26</sup> the Lord turn his face toward you and give you peace.`, translation: 'NIV', texts: { NIV: `<sup>24</sup> The Lord bless you and keep you; <sup>25</sup> the Lord make his face shine on you and be gracious to you; <sup>26</sup> the Lord turn his face toward you and give you peace.`, KJV: `<sup>24</sup> The Lord bless thee, and keep thee: <sup>25</sup> The Lord make his face shine upon thee, and be gracious unto thee: <sup>26</sup> The Lord lift up his countenance upon thee, and give thee peace.`, NLT: `<sup>24</sup> May the Lord bless you and protect you. <sup>25</sup> May the Lord smile on you and be gracious to you. <sup>26</sup> May the Lord show you his favor and give you his peace.` }, sortOrder: 18 });
    await upsertScripture({ competitionYearId: y2025.id, id: '28', reference: 'Deuteronomy 31:6', text: `<sup>6</sup> Be strong and courageous. Do not be afraid or terrified because of them, for the Lord your God goes with you; he will never leave you nor forsake you.`, translation: 'NIV', texts: { NIV: `<sup>6</sup> Be strong and courageous. Do not be afraid or terrified because of them, for the Lord your God goes with you; he will never leave you nor forsake you.`, KJV: `<sup>6</sup> Be strong and of a good courage, fear not, nor be afraid of them: for the Lord thy God, he it is that doth go with thee; he will not fail thee, nor forsake thee.`, NLT: `<sup>6</sup> So be strong and courageous! Do not be afraid and do not panic before them. For the Lord your God will personally go ahead of you. He will neither fail you nor abandon you.` }, sortOrder: 19 });
    await upsertScripture({ competitionYearId: y2025.id, id: '29', reference: 'Revelation 1:8', text: `<sup>8</sup> I am the Alpha and the Omega, says the Lord God, who is, and who was, and who is to come, the Almighty.`, translation: 'NIV', texts: { NIV: `<sup>8</sup> I am the Alpha and the Omega, says the Lord God, who is, and who was, and who is to come, the Almighty.`, KJV: `<sup>8</sup> I am Alpha and Omega, the beginning and the ending, saith the Lord, which is, and which was, and which is to come, the Almighty.`, NLT: `<sup>8</sup> I am the Alpha and the Omega—the beginning and the end, says the Lord God. I am the one who is, who always was, and who is still to come—the Almighty One.` }, sortOrder: 20 });
    await upsertScripture({ competitionYearId: y2025.id, id: '30', reference: 'Psalm 145:13', text: `<sup>13</sup> Your kingdom is an everlasting kingdom, and your dominion endures through all generations. The Lord is trustworthy in all he promises and faithful in all he does.`, translation: 'NIV', texts: { NIV: `<sup>13</sup> Your kingdom is an everlasting kingdom, and your dominion endures through all generations. The Lord is trustworthy in all he promises and faithful in all he does.`, KJV: `<sup>13</sup> Thy kingdom is an everlasting kingdom, and thy dominion endureth throughout all generations.`, NLT: `<sup>13</sup> For your kingdom is an everlasting kingdom. You rule throughout all generations. The Lord always keeps his promises; he is gracious in all he does.` }, sortOrder: 21 });
    await upsertScripture({ competitionYearId: y2025.id, id: '31', reference: 'John 6:35', text: `<sup>35</sup> Then Jesus declared, "I am the bread of life. Whoever comes to me will never go hungry, and whoever believes in me will never be thirsty.",`, translation: 'NIV', texts: { NIV: `<sup>35</sup> Then Jesus declared, "I am the bread of life. Whoever comes to me will never go hungry, and whoever believes in me will never be thirsty."`, KJV: `<sup>35</sup> And Jesus said unto them, I am the bread of life: he that cometh to me shall never hunger; and he that believeth on me shall never thirst.`, NLT: `<sup>35</sup> Jesus replied, “I am the bread of life. Whoever comes to me will never be hungry again. Whoever believes in me will never be thirsty.”` }, sortOrder: 22 });
    await upsertScripture({ competitionYearId: y2025.id, id: '32', reference: '1 Corinthians 13:13', text: `<sup>13</sup> And now these three remain: faith, hope and love. But the greatest of these is love.`, translation: 'NIV', texts: { NIV: `<sup>13</sup> And now these three remain: faith, hope and love. But the greatest of these is love.`, KJV: `<sup>13</sup> And now abideth faith, hope, charity, these three; but the greatest of these is charity.`, NLT: `<sup>13</sup> Three things will last forever—faith, hope, and love—and the greatest of these is love.` }, sortOrder: 23 });
    await upsertScripture({ competitionYearId: y2025.id, id: '33-34', reference: 'Hebrews 12:1-2', text: `<sup>1</sup> Therefore, since we are surrounded by such a great cloud of witnesses, let us throw off everything that hinders and the sin that so easily entangles. And let us run with perseverance the race marked out for us, <sup>2</sup> fixing our eyes on Jesus, the pioneer and perfecter of faith. For the joy set before him he endured the cross, scorning its shame, and sat down at the right hand of the throne of God.`, translation: 'NIV', texts: { NIV: `<sup>1</sup> Therefore, since we are surrounded by such a great cloud of witnesses, let us throw off everything that hinders and the sin that so easily entangles. And let us run with perseverance the race marked out for us, <sup>2</sup> fixing our eyes on Jesus, the pioneer and perfecter of faith. For the joy set before him he endured the cross, scorning its shame, and sat down at the right hand of the throne of God.`, KJV: `<sup>1</sup> Wherefore seeing we also are compassed about with so great a cloud of witnesses, let us lay aside every weight, and the sin which doth so easily beset us, and let us run with patience the race that is set before us, <sup>2</sup> Looking unto Jesus the author and finisher of our faith; who for the joy that was set before him endured the cross, despising the shame, and is set down at the right hand of the throne of God.`, NLT: `<sup>1</sup> Therefore, since we are surrounded by such a huge crowd of witnesses to the life of faith, let us strip off every weight that slows us down, especially the sin that so easily trips us up. And let us run with endurance the race God has set before us. <sup>2</sup> We do this by keeping our eyes on Jesus, the champion who initiates and perfects our faith. Because of the joy awaiting him, he endured the cross, disregarding its shame. Now he is seated in the place of honor beside God’s throne.` }, sortOrder: 24 });
    await upsertScripture({ competitionYearId: y2025.id, id: '35', reference: '2 Corinthians 12:9', text: `<sup>9</sup> But he said to me, "My grace is sufficient for you, for my power is made perfect in weakness." Therefore I will boast all the more gladly about my weaknesses, so that Christ's power may rest on me.`, translation: 'NIV', texts: { NIV: `<sup>9</sup> But he said to me, "My grace is sufficient for you, for my power is made perfect in weakness." Therefore I will boast all the more gladly about my weaknesses, so that Christ's power may rest on me.`, KJV: `<sup>9</sup> And he said unto me, My grace is sufficient for thee: for my strength is made perfect in weakness. Most gladly therefore will I rather glory in my infirmities, that the power of Christ may rest upon me.`, NLT: `<sup>9</sup> Each time he said, “My grace is all you need. My power works best in weakness.” So now I am glad to boast about my weaknesses, so that the power of Christ can work through me.` }, sortOrder: 25 });
    await upsertScripture({ competitionYearId: y2025.id, id: '36', reference: 'Colossians 3:5', text: `<sup>5</sup> Put to death, therefore, whatever belongs to your earthly nature: sexual immorality, impurity, lust, evil desires and greed, which is idolatry.`, translation: 'NIV', texts: { NIV: `<sup>5</sup> Put to death, therefore, whatever belongs to your earthly nature: sexual immorality, impurity, lust, evil desires and greed, which is idolatry.`, KJV: `<sup>5</sup> Mortify therefore your members which are upon the earth; fornication, uncleanness, inordinate affection, evil concupiscence, and covetousness, which is idolatry.`, NLT: `<sup>5</sup> So put to death the sinful, earthly things lurking within you. Have nothing to do with sexual immorality, impurity, lust, and evil desires. Don’t be greedy, for a greedy person is an idolater, worshiping the things of this world.` }, sortOrder: 26 });
    await upsertScripture({ competitionYearId: y2025.id, id: '37', reference: 'Colossians 3:8', text: `<sup>8</sup> But now you must also rid yourselves of all such things as these: anger, rage, malice, slander, and filthy language from your lips.`, translation: 'NIV', texts: { NIV: `<sup>8</sup> But now you must also rid yourselves of all such things as these: anger, rage, malice, slander, and filthy language from your lips.`, KJV: `<sup>8</sup> But now ye also put off all these; anger, wrath, malice, blasphemy, filthy communication out of your mouth.`, NLT: `<sup>8</sup> But now is the time to get rid of anger, rage, malicious behavior, slander, and dirty language.` }, sortOrder: 27 });
    await upsertScripture({ competitionYearId: y2025.id, id: '38', reference: 'Zephaniah 3:17', text: `<sup>17</sup> The Lord your God is with you, the Mighty Warrior who saves. He will take great delight in you; in his love he will no longer rebuke you, but will rejoice over you with singing.`, translation: 'NIV', texts: { NIV: `<sup>17</sup> The Lord your God is with you, the Mighty Warrior who saves. He will take great delight in you; in his love he will no longer rebuke you, but will rejoice over you with singing.`, KJV: `<sup>17</sup> The Lord thy God in the midst of thee is mighty; he will save, he will rejoice over thee with joy; he will rest in his love, he will joy over thee with singing.`, NLT: `<sup>17</sup> For the Lord your God is living among you. He is a mighty savior. He will take delight in you with gladness. With his love, he will calm all your fears. He will rejoice over you with joyful songs.` }, sortOrder: 28 });
    await upsertScripture({ competitionYearId: y2025.id, id: '39', reference: 'Psalm 51:10', text: `<sup>10</sup> Create in me a pure heart, O God, and renew a steadfast spirit within me.`, translation: 'NIV', texts: { NIV: `<sup>10</sup> Create in me a pure heart, O God, and renew a steadfast spirit within me.`, KJV: `<sup>10</sup> Create in me a clean heart, O God; and renew a right spirit within me.`, NLT: `<sup>10</sup> Create in me a clean heart, O God. Renew a loyal spirit within me.` }, sortOrder: 29 });
    await upsertScripture({ competitionYearId: y2025.id, id: '40-41', reference: 'Proverbs 16:3-4', text: `<sup>3</sup> Commit to the Lord whatever you do, and he will establish your plans. <sup>4</sup> The Lord works out everything to its proper end—even the wicked for a day of disaster.`, translation: 'NIV', texts: { NIV: `<sup>3</sup> Commit to the Lord whatever you do, and he will establish your plans. <sup>4</sup> The Lord works out everything to its proper end—even the wicked for a day of disaster.`, KJV: `<sup>3</sup> Commit thy works unto the Lord, and thy thoughts shall be established. <sup>4</sup> The Lord hath made all things for himself: yea, even the wicked for the day of evil.`, NLT: `<sup>3</sup> Commit your actions to the Lord, and your plans will succeed. <sup>4</sup> The Lord has made everything for his own purposes, even the wicked for a day of disaster.` }, sortOrder: 30 });
    await upsertScripture({ competitionYearId: y2025.id, id: '42', reference: 'Matthew 5:16', text: `<sup>16</sup> In the same way, let your light shine before others, that they may see your good deeds and glorify your Father in heaven.`, translation: 'NIV', texts: { NIV: `<sup>16</sup> In the same way, let your light shine before others, that they may see your good deeds and glorify your Father in heaven.`, KJV: `<sup>16</sup> Let your light so shine before men, that they may see your good works, and glorify your Father which is in heaven.`, NLT: `<sup>16</sup> In the same way, let your good deeds shine out for all to see, so that everyone will praise your heavenly Father.` }, sortOrder: 31 });
    await upsertScripture({ competitionYearId: y2025.id, id: '43-44', reference: 'Proverbs 16:18-19', text: `<sup>18</sup> Pride goes before destruction, a haughty spirit before a fall. <sup>19</sup> Better to be lowly in spirit along with the oppressed than to share plunder with the proud.`, translation: 'NIV', texts: { NIV: `<sup>18</sup> Pride goes before destruction, a haughty spirit before a fall. <sup>19</sup> Better to be lowly in spirit along with the oppressed than to share plunder with the proud.`, KJV: `<sup>18</sup> Pride goeth before destruction, and an haughty spirit before a fall. <sup>19</sup> Better it is to be of an humble spirit with the lowly, than to divide the spoil with the proud.`, NLT: `<sup>18</sup> Pride goes before destruction, and haughtiness before a fall. <sup>19</sup> Better to live humbly with the poor than to share plunder with the proud.` }, sortOrder: 32 });
    await upsertScripture({ competitionYearId: y2025.id, id: '45', reference: 'Ephesians 2:10', text: `<sup>10</sup> For we are God’s handiwork, created in Christ Jesus to do good works, which God prepared in advance for us to do.`, translation: 'NIV', texts: { NIV: `<sup>10</sup> For we are God’s handiwork, created in Christ Jesus to do good works, which God prepared in advance for us to do.`, KJV: `<sup>10</sup> For we are his workmanship, created in Christ Jesus unto good works, which God hath before ordained that we should walk in them.`, NLT: `<sup>10</sup> For we are God’s masterpiece. He has created us anew in Christ Jesus, so we can do the good things he planned for us long ago.` }, sortOrder: 33 });
    await upsertScripture({ competitionYearId: y2025.id, id: '46-47', reference: 'Galatians 5:22-23', text: `<sup>22</sup> But the fruit of the Spirit is love, joy, peace, forbearance, kindness, goodness, faithfulness, <sup>23</sup> gentleness and self-control. Against such things there is no law.`, translation: 'NIV', texts: { NIV: `<sup>22</sup> But the fruit of the Spirit is love, joy, peace, forbearance, kindness, goodness, faithfulness, <sup>23</sup> gentleness and self-control. Against such things there is no law.`, KJV: `<sup>22</sup> But the fruit of the Spirit is love, joy, peace, longsuffering, gentleness, goodness, faith, <sup>23</sup> Meekness, temperance: against such there is no law.`, NLT: `<sup>22</sup> But the Holy Spirit produces this kind of fruit in our lives: love, joy, peace, patience, kindness, goodness, faithfulness, <sup>23</sup> gentleness, and self-control. There is no law against these things!` }, sortOrder: 34 });
    await upsertScripture({ competitionYearId: y2025.id, id: '48-52', reference: '1 Thessalonians 5:19-22', text: `<sup>19</sup> Do not quench the Spirit. <sup>20</sup> Do not treat prophecies with contempt <sup>21</sup> but test them all; hold on to what is good, <sup>22</sup> reject every kind of evil.`, translation: 'NIV', texts: { NIV: `<sup>19</sup> Do not quench the Spirit. <sup>20</sup> Do not treat prophecies with contempt <sup>21</sup> but test them all; hold on to what is good, <sup>22</sup> reject every kind of evil.`, KJV: `<sup>19</sup> Quench not the Spirit. <sup>20</sup> Despise not prophesyings. <sup>21</sup> Prove all things; hold fast that which is good. <sup>22</sup> Abstain from all appearance of evil.`, NLT: `<sup>19</sup> Do not stifle the Holy Spirit. <sup>20</sup> Do not scoff at prophecies, <sup>21</sup> but test everything that is said. Hold on to what is good. <sup>22</sup> Stay away from every kind of evil.` }, sortOrder: 35 });

    // grade rules
    await createGradeRule({ competitionYearId: y2025.id, minGrade: 1, maxGrade: 6, type: 'scripture', targetCount: 20 });
    await createGradeRule({ competitionYearId: y2025.id, minGrade: 7, maxGrade: 12, type: 'essay', promptText: 'Explain the central theme of Ephesians 2', instructions: '500 words' });

    // seed a couple of households/children if none exist
    const households = await db.households.toArray();
    if (households.length === 0) {
        const hhId = crypto.randomUUID();
        await db.households.add({ household_id: hhId, name: 'Seed Family', created_at: now, updated_at: now });
        const childA = { child_id: crypto.randomUUID(), household_id: hhId, first_name: 'Alice', last_name: 'Seed', grade: '3', is_active: true, created_at: now, updated_at: now };
        const childB = { child_id: crypto.randomUUID(), household_id: hhId, first_name: 'Bob', last_name: 'Seed', grade: '8', is_active: true, created_at: now, updated_at: now };
        await db.children.bulkAdd([childA, childB]);

        // enroll both in 2025
        await enrollChildInBibleBee(childA.child_id, y2025.id);
        await enrollChildInBibleBee(childB.child_id, y2025.id);
    }
}
