name: CI - DB migrations & FK checks

on:
  pull_request:
  push:
    branches: [main]

jobs:
  db-fk-check:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 54322:5432
        options: >-
          --health-cmd "pg_isready -U postgres" --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Wait for Postgres
        run: |
          echo "Waiting for Postgres to be ready..."
          for i in {1..30}; do
            pg_isready -h localhost -p 54322 -U postgres && break
            sleep 1
          done

      - name: Set up psql env
        run: |
          echo "PGHOST=localhost" >> $GITHUB_ENV
          echo "PGPORT=54322" >> $GITHUB_ENV
          echo "PGUSER=postgres" >> $GITHUB_ENV
          echo "PGPASSWORD=postgres" >> $GITHUB_ENV
          echo "PGDATABASE=postgres" >> $GITHUB_ENV

      - name: Run SQL migrations
        run: |
          for f in supabase/migrations/*.sql; do
            echo "Applying $f" && psql -h localhost -p 54322 -U postgres -d postgres -f "$f"
          done

      - name: Make check script executable
        run: chmod +x scripts/db/check_fks.sh

      - name: Run FK integrity checks
        run: scripts/db/check_fks.sh
