name: Daily Digest

on:
  schedule:
    # Run at 7:00 AM ET (11:00 UTC during EDT, 12:00 UTC during EST)
    # Using 11:00 UTC as it covers EDT; adjust for EST if needed
    - cron: '0 11 * * *'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run against'
        required: false
        default: 'PROD'
        type: choice
        options:
          - 'PROD'
          - 'UAT'
      dry_run:
        description: 'Run in dry mode (no emails sent)'
        required: false
        default: false
        type: boolean
      test_mode:
        description: 'Run in test mode (emails only sent to monitor addresses)'
        required: false
        default: false
        type: boolean

jobs:
  digest-prod:
    if: ${{ inputs.environment == 'PROD' || inputs.environment == '' }}
    runs-on: ubuntu-latest
    env:
      ENVIRONMENT: PROD
      DRY_RUN: ${{ inputs.dry_run && 'true' || 'false' }}
      TEST_MODE: ${{ inputs.test_mode && 'true' || 'false' }}
      SUPABASE_URL: ${{ secrets.PROD_SUPABASE_URL }}
      SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.PROD_SUPABASE_SERVICE_ROLE_KEY }}
      MJ_API_KEY: ${{ secrets.PROD_MJ_API_KEY }}
      MJ_API_SECRET: ${{ secrets.PROD_MJ_API_SECRET }}
      FROM_EMAIL: ${{ secrets.PROD_FROM_EMAIL }}
      MONITOR_EMAILS: ${{ secrets.PROD_MONITOR_EMAILS }}
      EMAIL_MODE: ${{ secrets.PROD_EMAIL_MODE || 'mailjet' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run daily digest (PROD)
        run: |
          echo "Running PROD daily digest..."
          echo "Environment: $ENVIRONMENT"
          echo "Dry run: $DRY_RUN"
          echo "Test mode: $TEST_MODE"
          node scripts/dailyDigest.js

      - name: Log completion
        if: success()
        run: |
          echo "PROD daily digest completed successfully at $(date)"
          echo "Dry run: $DRY_RUN"
          echo "Test mode: $TEST_MODE"

      - name: Log failure
        if: failure()
        run: |
          echo "PROD daily digest failed at $(date)"
          echo "Dry run: $DRY_RUN"
          echo "Test mode: $TEST_MODE"

  digest-uat:
    if: ${{ inputs.environment == 'UAT' }}
    runs-on: ubuntu-latest
    env:
      ENVIRONMENT: UAT
      DRY_RUN: ${{ inputs.dry_run && 'true' || 'false' }}
      TEST_MODE: ${{ inputs.test_mode && 'true' || 'false' }}
      SUPABASE_URL: ${{ secrets.UAT_SUPABASE_URL }}
      SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.UAT_SUPABASE_SERVICE_ROLE_KEY }}
      MJ_API_KEY: ${{ secrets.UAT_MJ_API_KEY }}
      MJ_API_SECRET: ${{ secrets.UAT_MJ_API_SECRET }}
      FROM_EMAIL: ${{ secrets.UAT_FROM_EMAIL }}
      MONITOR_EMAILS: ${{ secrets.UAT_MONITOR_EMAILS }}
      EMAIL_MODE: ${{ secrets.UAT_EMAIL_MODE || 'mailjet' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run daily digest (UAT)
        run: |
          echo "Running UAT daily digest..."
          echo "Environment: $ENVIRONMENT"
          echo "Dry run: $DRY_RUN"
          echo "Test mode: $TEST_MODE"
          node scripts/dailyDigest.js

      - name: Log completion
        if: success()
        run: |
          echo "UAT daily digest completed successfully at $(date)"
          echo "Dry run: $DRY_RUN"
          echo "Test mode: $TEST_MODE"

      - name: Log failure
        if: failure()
        run: |
          echo "UAT daily digest failed at $(date)"
          echo "Dry run: $DRY_RUN"
          echo "Test mode: $TEST_MODE"
