name: Generate Supabase Types (CI)

on:
  workflow_dispatch:
    inputs:
      commit:
        description: 'If true, commit and push generated types to a branch and open a PR'
        required: false
        default: 'false'

permissions:
  contents: write
  pull-requests: write

jobs:
  gen-types:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Install supabase CLI from latest release and generate types
        id: gen
        run: |
          set -euo pipefail
          echo "Installing required packages"
          apt-get update -qq && apt-get install -y -qq curl ca-certificates jq tar

          echo "Querying GitHub Releases for supabase/cli latest release"
          RELEASE_JSON=$(curl -sSL "https://api.github.com/repos/supabase/cli/releases/latest")
          ASSET_URL=$(echo "$RELEASE_JSON" | jq -r '.assets[] | select(.name | test("linux_amd64.tar.gz")) | .browser_download_url' | head -n1)
          if [ -z "$ASSET_URL" ] || [ "$ASSET_URL" = "null" ]; then
            echo "Could not find linux_amd64 asset in latest release" >&2
            echo "$RELEASE_JSON" | jq -r '.assets[] | .name' || true
            exit 2
          fi

          echo "Downloading supabase CLI asset: $ASSET_URL"
          curl -fSL --retry 3 --retry-delay 2 "$ASSET_URL" -o /tmp/supabase.tar.gz
          tar -xzf /tmp/supabase.tar.gz -C /tmp
          chmod +x /tmp/supabase || true

          SUPABASE_BIN=/tmp/supabase
          echo "Using supabase binary: $SUPABASE_BIN"
          $SUPABASE_BIN --version || true
          echo "Running supabase gen types typescript --local"
          $SUPABASE_BIN gen types typescript --local

      - name: Ensure generated file exists
        run: |
          if [ ! -f src/lib/database/supabase-types.ts ]; then
            echo "Generated types file not found" >&2
            ls -la src/lib/database || true
            exit 1
          fi

      - name: Upload generated types artifact
        uses: actions/upload-artifact@v4
        with:
          name: supabase-types
          path: src/lib/database/supabase-types.ts

      - name: Commit and open PR (optional)
        if: ${{ github.event.inputs.commit == 'true' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -euo pipefail
          BRANCH=ci/gen-supabase-types-$(date +%s)
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout -b "$BRANCH"
          git add src/lib/database/supabase-types.ts
          git commit -m "chore(gen): regenerate supabase types"
          git push --set-upstream origin "$BRANCH"
          echo "Creating PR..."
          API_URL="https://api.github.com/repos/${{ github.repository }}/pulls"
          BODY=$(jq -n --arg title "chore(gen): regenerate supabase types" --arg head "$BRANCH" --arg base "develop" '{title:$title,head:$head,base:$base,body:"Auto-generated supabase types (CI)"}')
          curl -s -X POST -H "Authorization: token $GITHUB_TOKEN" -H "Accept: application/vnd.github+json" $API_URL -d "$BODY" | jq -r '.html_url'
