name: Generate Supabase Types (CI)

on:
  workflow_dispatch:
    inputs:
      commit:
        description: 'If true, commit and push generated types to a branch and open a PR'
        required: false
        default: 'false'

permissions:
  contents: write
  pull-requests: write

jobs:
  gen-types:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Install Supabase CLI
        id: install-supabase
        run: |
          set -euo pipefail
          # Create bin directory in home if it doesn't exist
          mkdir -p "$HOME/.bin"

          # Download the latest version for Linux and extract to $HOME/.bin
          curl -s -L https://github.com/supabase/cli/releases/latest/download/supabase_linux_amd64.tar.gz | tar -xz -C "$HOME/.bin"

          # Make it executable
          chmod +x "$HOME/.bin/supabase"

          # Add to PATH for subsequent steps
          export PATH="$HOME/.bin:$PATH"
          echo "$HOME/.bin" >> $GITHUB_PATH

      - name: Generate types using Supabase CLI
        id: gen
        run: |
          set -euo pipefail
          echo "Using supabase binary at: $(which supabase || echo 'not found')"
          supabase --version || true
          echo "Running supabase gen types typescript --local"
          supabase gen types typescript --local

      - name: Ensure generated file exists
        run: |
          if [ ! -f src/lib/database/supabase-types.ts ]; then
            echo "Generated types file not found" >&2
            ls -la src/lib/database || true
            exit 1
          fi

      - name: Upload generated types artifact
        uses: actions/upload-artifact@v4
        with:
          name: supabase-types
          path: src/lib/database/supabase-types.ts

      - name: Commit and open PR (optional)
        if: ${{ github.event.inputs.commit == 'true' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -euo pipefail
          BRANCH=ci/gen-supabase-types-$(date +%s)
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout -b "$BRANCH"
          git add src/lib/database/supabase-types.ts
          git commit -m "chore(gen): regenerate supabase types"
          git push --set-upstream origin "$BRANCH"
          echo "Creating PR..."
          API_URL="https://api.github.com/repos/${{ github.repository }}/pulls"
          BODY=$(jq -n --arg title "chore(gen): regenerate supabase types" --arg head "$BRANCH" --arg base "develop" '{title:$title,head:$head,base:$base,body:"Auto-generated supabase types (CI)"}')
          curl -s -X POST -H "Authorization: token $GITHUB_TOKEN" -H "Accept: application/vnd.github+json" $API_URL -d "$BODY" | jq -r '.html_url'
