# .github/workflows/prod-deploy.yml
name: PROD deploy (manual approval)
on:
  workflow_dispatch: {}
permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - uses: actions/checkout@v4
      - name: Install Postgres client
        run: sudo apt-get update && sudo apt-get install -y postgresql-client
      - name: Verify DB URL (sslmode)
        run: |
          if [[ "${{ secrets.PROD_DATABASE_URL }}" != *"sslmode="* ]]; then
            echo "ERROR: PROD_DATABASE_URL must include sslmode=require."; exit 1; fi
      - name: List unapplied migrations (dry-run)
        env:
          DATABASE_URL: ${{ secrets.PROD_DATABASE_URL }}
        run: |
          chmod +x scripts/db/list_unapplied_migrations.sh
          scripts/db/list_unapplied_migrations.sh "$DATABASE_URL" "supabase/migrations"
      - name: Apply migrations
        env:
          DATABASE_URL: ${{ secrets.PROD_DATABASE_URL }}
        run: |
          chmod +x scripts/db/apply_migrations_safe.sh
          scripts/db/apply_migrations_safe.sh "$DATABASE_URL" "supabase/migrations"
      - name: Snapshot schema (pg_dump -s)
        env:
          DATABASE_URL: ${{ secrets.PROD_DATABASE_URL }}
        run: |
          mkdir -p snapshots
          SNAPSHOT="snapshots/schema-prod-$(date +'%Y%m%d-%H%M%S').sql"
          pg_dump --schema-only --no-owner --no-privileges --dbname="$DATABASE_URL" > "$SNAPSHOT"
      - name: Upload schema snapshot
        uses: actions/upload-artifact@v4
        with:
          name: prod-schema-snapshot
          path: snapshots/
          retention-days: 30
