name: PROD deploy (manual approval)

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://gatherkidslive.com
    steps:
      - uses: actions/checkout@v4
      - name: Install psql
        run: sudo apt-get update && sudo apt-get install -y postgresql-client
      - name: Apply migrations (manual approval required by environment)
        env:
          DATABASE_URL: ${{ secrets.PROD_DATABASE_URL }}
        run: |
          chmod +x scripts/db/apply_migrations_safe.sh
          ./scripts/db/apply_migrations_safe.sh "$DATABASE_URL"
*** End Patch
